#!/bin/bash

# This belongs in /usr/local/bin/yubikey-luks-unlock

# Path to the LUKS container
DEVICE="${DEVICE}" # Placeholder to be replaced by installer
# Name of the unlocked mapper
MAPPER="${MAPPER}" # Placeholder to be replaced by installer
# Path where the unlocked container will be mounted
MOUNT_POINT="${MOUNT_POINT}" # Placeholder to be replaced by installer

echo "Sending challenge to YubiKey..."

# Send a challenge to the YubiKey and get the response
YUBIKEY_RESPONSE=$(ykchalresp -2 "LUKSChallenge")

echo "YubiKey Response: $YUBIKEY_RESPONSE"

# Check the response
if [ -z "$YUBIKEY_RESPONSE" ]; then
    echo "No response received from YubiKey."
    exit 1
fi

echo "Attempting to unlock the container with the YubiKey response..."

# Attempt to unlock the container with the received YubiKey response
echo "$YUBIKEY_RESPONSE" | cryptsetup open $DEVICE $MAPPER
# Check if the device was successfully unlocked
if [ $? -eq 0 ]; then
    echo "Container successfully unlocked. Attempting to mount..."
    # Mount the container if it was successfully unlocked
    sudo mount /dev/mapper/$MAPPER $MOUNT_POINT
    if [ $? -eq 0 ]; then
        echo "Container successfully mounted at $MOUNT_POINT."
    else
        echo "Error mounting the container."
    fi
else
    echo "Decryption failed."
    exit 1
fi
